
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "algorithm_core_api",
    srcs = [
       "timer.cpp" ,    
        "profiler.cpp" ,    
    ],
    hdrs = [
       "timer.h" ,    
        "profiler.h" ,    
    ],
    deps = [
            "//projects/adas/algorithm:algorithm_header",   
            "//projects/adas/algorithm/core/caffe:algorithm_caffe_api",   
             "//projects/adas/algorithm/core/util:algorithm_util_api",             
    ],
)
