// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adapter_config.proto

#ifndef PROTOBUF_INCLUDED_adapter_5fconfig_2eproto
#define PROTOBUF_INCLUDED_adapter_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_adapter_5fconfig_2eproto 

namespace protobuf_adapter_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_adapter_5fconfig_2eproto
namespace watrix {
namespace proto {
class AdapterConfig;
class AdapterConfigDefaultTypeInternal;
extern AdapterConfigDefaultTypeInternal _AdapterConfig_default_instance_;
class AdapterManagerConfig;
class AdapterManagerConfigDefaultTypeInternal;
extern AdapterManagerConfigDefaultTypeInternal _AdapterManagerConfig_default_instance_;
}  // namespace proto
}  // namespace watrix
namespace google {
namespace protobuf {
template<> ::watrix::proto::AdapterConfig* Arena::CreateMaybeMessage<::watrix::proto::AdapterConfig>(Arena*);
template<> ::watrix::proto::AdapterManagerConfig* Arena::CreateMaybeMessage<::watrix::proto::AdapterManagerConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace watrix {
namespace proto {

enum AdapterConfig_MessageType {
  AdapterConfig_MessageType_POINT_CLOUD = 1,
  AdapterConfig_MessageType_VLP16_POINT_CLOUD = 2,
  AdapterConfig_MessageType_CAMERA_IMAGE = 3,
  AdapterConfig_MessageType_SYNC_CAMERA_RESULT = 4,
  AdapterConfig_MessageType_SYNC_PERCEPTION_RESULT = 5,
  AdapterConfig_MessageType_LIDAR_IMAGE_RESULT = 6,
  AdapterConfig_MessageType_SEND_RESULT = 7
};
bool AdapterConfig_MessageType_IsValid(int value);
const AdapterConfig_MessageType AdapterConfig_MessageType_MessageType_MIN = AdapterConfig_MessageType_POINT_CLOUD;
const AdapterConfig_MessageType AdapterConfig_MessageType_MessageType_MAX = AdapterConfig_MessageType_SEND_RESULT;
const int AdapterConfig_MessageType_MessageType_ARRAYSIZE = AdapterConfig_MessageType_MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* AdapterConfig_MessageType_descriptor();
inline const ::std::string& AdapterConfig_MessageType_Name(AdapterConfig_MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    AdapterConfig_MessageType_descriptor(), value);
}
inline bool AdapterConfig_MessageType_Parse(
    const ::std::string& name, AdapterConfig_MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AdapterConfig_MessageType>(
    AdapterConfig_MessageType_descriptor(), name, value);
}
enum AdapterConfig_Mode {
  AdapterConfig_Mode_RECEIVE_ONLY = 0,
  AdapterConfig_Mode_PUBLISH_ONLY = 1,
  AdapterConfig_Mode_DUPLEX = 2
};
bool AdapterConfig_Mode_IsValid(int value);
const AdapterConfig_Mode AdapterConfig_Mode_Mode_MIN = AdapterConfig_Mode_RECEIVE_ONLY;
const AdapterConfig_Mode AdapterConfig_Mode_Mode_MAX = AdapterConfig_Mode_DUPLEX;
const int AdapterConfig_Mode_Mode_ARRAYSIZE = AdapterConfig_Mode_Mode_MAX + 1;

const ::google::protobuf::EnumDescriptor* AdapterConfig_Mode_descriptor();
inline const ::std::string& AdapterConfig_Mode_Name(AdapterConfig_Mode value) {
  return ::google::protobuf::internal::NameOfEnum(
    AdapterConfig_Mode_descriptor(), value);
}
inline bool AdapterConfig_Mode_Parse(
    const ::std::string& name, AdapterConfig_Mode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AdapterConfig_Mode>(
    AdapterConfig_Mode_descriptor(), name, value);
}
// ===================================================================

class AdapterConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:watrix.proto.AdapterConfig) */ {
 public:
  AdapterConfig();
  virtual ~AdapterConfig();

  AdapterConfig(const AdapterConfig& from);

  inline AdapterConfig& operator=(const AdapterConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AdapterConfig(AdapterConfig&& from) noexcept
    : AdapterConfig() {
    *this = ::std::move(from);
  }

  inline AdapterConfig& operator=(AdapterConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdapterConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdapterConfig* internal_default_instance() {
    return reinterpret_cast<const AdapterConfig*>(
               &_AdapterConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AdapterConfig* other);
  friend void swap(AdapterConfig& a, AdapterConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdapterConfig* New() const final {
    return CreateMaybeMessage<AdapterConfig>(NULL);
  }

  AdapterConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AdapterConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AdapterConfig& from);
  void MergeFrom(const AdapterConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdapterConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef AdapterConfig_MessageType MessageType;
  static const MessageType POINT_CLOUD =
    AdapterConfig_MessageType_POINT_CLOUD;
  static const MessageType VLP16_POINT_CLOUD =
    AdapterConfig_MessageType_VLP16_POINT_CLOUD;
  static const MessageType CAMERA_IMAGE =
    AdapterConfig_MessageType_CAMERA_IMAGE;
  static const MessageType SYNC_CAMERA_RESULT =
    AdapterConfig_MessageType_SYNC_CAMERA_RESULT;
  static const MessageType SYNC_PERCEPTION_RESULT =
    AdapterConfig_MessageType_SYNC_PERCEPTION_RESULT;
  static const MessageType LIDAR_IMAGE_RESULT =
    AdapterConfig_MessageType_LIDAR_IMAGE_RESULT;
  static const MessageType SEND_RESULT =
    AdapterConfig_MessageType_SEND_RESULT;
  static inline bool MessageType_IsValid(int value) {
    return AdapterConfig_MessageType_IsValid(value);
  }
  static const MessageType MessageType_MIN =
    AdapterConfig_MessageType_MessageType_MIN;
  static const MessageType MessageType_MAX =
    AdapterConfig_MessageType_MessageType_MAX;
  static const int MessageType_ARRAYSIZE =
    AdapterConfig_MessageType_MessageType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MessageType_descriptor() {
    return AdapterConfig_MessageType_descriptor();
  }
  static inline const ::std::string& MessageType_Name(MessageType value) {
    return AdapterConfig_MessageType_Name(value);
  }
  static inline bool MessageType_Parse(const ::std::string& name,
      MessageType* value) {
    return AdapterConfig_MessageType_Parse(name, value);
  }

  typedef AdapterConfig_Mode Mode;
  static const Mode RECEIVE_ONLY =
    AdapterConfig_Mode_RECEIVE_ONLY;
  static const Mode PUBLISH_ONLY =
    AdapterConfig_Mode_PUBLISH_ONLY;
  static const Mode DUPLEX =
    AdapterConfig_Mode_DUPLEX;
  static inline bool Mode_IsValid(int value) {
    return AdapterConfig_Mode_IsValid(value);
  }
  static const Mode Mode_MIN =
    AdapterConfig_Mode_Mode_MIN;
  static const Mode Mode_MAX =
    AdapterConfig_Mode_Mode_MAX;
  static const int Mode_ARRAYSIZE =
    AdapterConfig_Mode_Mode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Mode_descriptor() {
    return AdapterConfig_Mode_descriptor();
  }
  static inline const ::std::string& Mode_Name(Mode value) {
    return AdapterConfig_Mode_Name(value);
  }
  static inline bool Mode_Parse(const ::std::string& name,
      Mode* value) {
    return AdapterConfig_Mode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional string topic = 4;
  bool has_topic() const;
  void clear_topic();
  static const int kTopicFieldNumber = 4;
  const ::std::string& topic() const;
  void set_topic(const ::std::string& value);
  #if LANG_CXX11
  void set_topic(::std::string&& value);
  #endif
  void set_topic(const char* value);
  void set_topic(const char* value, size_t size);
  ::std::string* mutable_topic();
  ::std::string* release_topic();
  void set_allocated_topic(::std::string* topic);

  // required .watrix.proto.AdapterConfig.Mode mode = 2;
  bool has_mode() const;
  void clear_mode();
  static const int kModeFieldNumber = 2;
  ::watrix::proto::AdapterConfig_Mode mode() const;
  void set_mode(::watrix::proto::AdapterConfig_Mode value);

  // required .watrix.proto.AdapterConfig.MessageType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::watrix::proto::AdapterConfig_MessageType type() const;
  void set_type(::watrix::proto::AdapterConfig_MessageType value);

  // optional int32 message_history_limit = 3 [default = 10];
  bool has_message_history_limit() const;
  void clear_message_history_limit();
  static const int kMessageHistoryLimitFieldNumber = 3;
  ::google::protobuf::int32 message_history_limit() const;
  void set_message_history_limit(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:watrix.proto.AdapterConfig)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_mode();
  void clear_has_mode();
  void set_has_message_history_limit();
  void clear_has_message_history_limit();
  void set_has_topic();
  void clear_has_topic();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr topic_;
  int mode_;
  int type_;
  ::google::protobuf::int32 message_history_limit_;
  friend struct ::protobuf_adapter_5fconfig_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AdapterManagerConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:watrix.proto.AdapterManagerConfig) */ {
 public:
  AdapterManagerConfig();
  virtual ~AdapterManagerConfig();

  AdapterManagerConfig(const AdapterManagerConfig& from);

  inline AdapterManagerConfig& operator=(const AdapterManagerConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AdapterManagerConfig(AdapterManagerConfig&& from) noexcept
    : AdapterManagerConfig() {
    *this = ::std::move(from);
  }

  inline AdapterManagerConfig& operator=(AdapterManagerConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdapterManagerConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdapterManagerConfig* internal_default_instance() {
    return reinterpret_cast<const AdapterManagerConfig*>(
               &_AdapterManagerConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AdapterManagerConfig* other);
  friend void swap(AdapterManagerConfig& a, AdapterManagerConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdapterManagerConfig* New() const final {
    return CreateMaybeMessage<AdapterManagerConfig>(NULL);
  }

  AdapterManagerConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AdapterManagerConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AdapterManagerConfig& from);
  void MergeFrom(const AdapterManagerConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdapterManagerConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .watrix.proto.AdapterConfig config = 1;
  int config_size() const;
  void clear_config();
  static const int kConfigFieldNumber = 1;
  ::watrix::proto::AdapterConfig* mutable_config(int index);
  ::google::protobuf::RepeatedPtrField< ::watrix::proto::AdapterConfig >*
      mutable_config();
  const ::watrix::proto::AdapterConfig& config(int index) const;
  ::watrix::proto::AdapterConfig* add_config();
  const ::google::protobuf::RepeatedPtrField< ::watrix::proto::AdapterConfig >&
      config() const;

  // @@protoc_insertion_point(class_scope:watrix.proto.AdapterManagerConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::watrix::proto::AdapterConfig > config_;
  friend struct ::protobuf_adapter_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AdapterConfig

// required .watrix.proto.AdapterConfig.MessageType type = 1;
inline bool AdapterConfig::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AdapterConfig::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AdapterConfig::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AdapterConfig::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::watrix::proto::AdapterConfig_MessageType AdapterConfig::type() const {
  // @@protoc_insertion_point(field_get:watrix.proto.AdapterConfig.type)
  return static_cast< ::watrix::proto::AdapterConfig_MessageType >(type_);
}
inline void AdapterConfig::set_type(::watrix::proto::AdapterConfig_MessageType value) {
  assert(::watrix::proto::AdapterConfig_MessageType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:watrix.proto.AdapterConfig.type)
}

// required .watrix.proto.AdapterConfig.Mode mode = 2;
inline bool AdapterConfig::has_mode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AdapterConfig::set_has_mode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AdapterConfig::clear_has_mode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AdapterConfig::clear_mode() {
  mode_ = 0;
  clear_has_mode();
}
inline ::watrix::proto::AdapterConfig_Mode AdapterConfig::mode() const {
  // @@protoc_insertion_point(field_get:watrix.proto.AdapterConfig.mode)
  return static_cast< ::watrix::proto::AdapterConfig_Mode >(mode_);
}
inline void AdapterConfig::set_mode(::watrix::proto::AdapterConfig_Mode value) {
  assert(::watrix::proto::AdapterConfig_Mode_IsValid(value));
  set_has_mode();
  mode_ = value;
  // @@protoc_insertion_point(field_set:watrix.proto.AdapterConfig.mode)
}

// optional int32 message_history_limit = 3 [default = 10];
inline bool AdapterConfig::has_message_history_limit() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AdapterConfig::set_has_message_history_limit() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AdapterConfig::clear_has_message_history_limit() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AdapterConfig::clear_message_history_limit() {
  message_history_limit_ = 10;
  clear_has_message_history_limit();
}
inline ::google::protobuf::int32 AdapterConfig::message_history_limit() const {
  // @@protoc_insertion_point(field_get:watrix.proto.AdapterConfig.message_history_limit)
  return message_history_limit_;
}
inline void AdapterConfig::set_message_history_limit(::google::protobuf::int32 value) {
  set_has_message_history_limit();
  message_history_limit_ = value;
  // @@protoc_insertion_point(field_set:watrix.proto.AdapterConfig.message_history_limit)
}

// optional string topic = 4;
inline bool AdapterConfig::has_topic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AdapterConfig::set_has_topic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AdapterConfig::clear_has_topic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AdapterConfig::clear_topic() {
  topic_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_topic();
}
inline const ::std::string& AdapterConfig::topic() const {
  // @@protoc_insertion_point(field_get:watrix.proto.AdapterConfig.topic)
  return topic_.GetNoArena();
}
inline void AdapterConfig::set_topic(const ::std::string& value) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:watrix.proto.AdapterConfig.topic)
}
#if LANG_CXX11
inline void AdapterConfig::set_topic(::std::string&& value) {
  set_has_topic();
  topic_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:watrix.proto.AdapterConfig.topic)
}
#endif
inline void AdapterConfig::set_topic(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:watrix.proto.AdapterConfig.topic)
}
inline void AdapterConfig::set_topic(const char* value, size_t size) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:watrix.proto.AdapterConfig.topic)
}
inline ::std::string* AdapterConfig::mutable_topic() {
  set_has_topic();
  // @@protoc_insertion_point(field_mutable:watrix.proto.AdapterConfig.topic)
  return topic_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AdapterConfig::release_topic() {
  // @@protoc_insertion_point(field_release:watrix.proto.AdapterConfig.topic)
  if (!has_topic()) {
    return NULL;
  }
  clear_has_topic();
  return topic_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AdapterConfig::set_allocated_topic(::std::string* topic) {
  if (topic != NULL) {
    set_has_topic();
  } else {
    clear_has_topic();
  }
  topic_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic);
  // @@protoc_insertion_point(field_set_allocated:watrix.proto.AdapterConfig.topic)
}

// -------------------------------------------------------------------

// AdapterManagerConfig

// repeated .watrix.proto.AdapterConfig config = 1;
inline int AdapterManagerConfig::config_size() const {
  return config_.size();
}
inline void AdapterManagerConfig::clear_config() {
  config_.Clear();
}
inline ::watrix::proto::AdapterConfig* AdapterManagerConfig::mutable_config(int index) {
  // @@protoc_insertion_point(field_mutable:watrix.proto.AdapterManagerConfig.config)
  return config_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::watrix::proto::AdapterConfig >*
AdapterManagerConfig::mutable_config() {
  // @@protoc_insertion_point(field_mutable_list:watrix.proto.AdapterManagerConfig.config)
  return &config_;
}
inline const ::watrix::proto::AdapterConfig& AdapterManagerConfig::config(int index) const {
  // @@protoc_insertion_point(field_get:watrix.proto.AdapterManagerConfig.config)
  return config_.Get(index);
}
inline ::watrix::proto::AdapterConfig* AdapterManagerConfig::add_config() {
  // @@protoc_insertion_point(field_add:watrix.proto.AdapterManagerConfig.config)
  return config_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::watrix::proto::AdapterConfig >&
AdapterManagerConfig::config() const {
  // @@protoc_insertion_point(field_list:watrix.proto.AdapterManagerConfig.config)
  return config_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace watrix

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::watrix::proto::AdapterConfig_MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::watrix::proto::AdapterConfig_MessageType>() {
  return ::watrix::proto::AdapterConfig_MessageType_descriptor();
}
template <> struct is_proto_enum< ::watrix::proto::AdapterConfig_Mode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::watrix::proto::AdapterConfig_Mode>() {
  return ::watrix::proto::AdapterConfig_Mode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_adapter_5fconfig_2eproto
