load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "test_boost",
    srcs = [
        "test_boost.cpp",
    ],
    deps = [
        "@boost",
    ],
)

cpplint()
