
package(default_visibility = ["//visibility:public"])

# load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_binary","go_test","go_source")

# go_library(
#     name = "go_cyber",
#     srcs = [
#         "cyber.go",
#     ],
#     cgo = 1,

#     deps = [
#     ],
#     importpath = "cyber/go_wrapper",
# )

# go_binary(
#     name = "test_cyber_go",
#     embed = [":go_cyber"],
#     srcs = [
#         "test_go.go",
#     ],
#     # clinkopts=[],
#     # linkmode = "normal",
#     # deps = [
#     #     "go_cyber",
#     # ],
# )
