load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base_adas_detector",
    hdrs = [
        "base_init_options.h",
        "base_adas_detector.h",
    ],
    deps = [

    ],
)

cpplint()
