// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: NicSysHisRpc.proto
#ifndef GRPC_NicSysHisRpc_2eproto__INCLUDED
#define GRPC_NicSysHisRpc_2eproto__INCLUDED

#include "NicSysHisRpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace NicSys_Hisd {

class HisdService final {
 public:
  static constexpr char const* service_full_name() {
    return "NicSys_Hisd.HisdService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status His_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::NicSys_Hisd::psHisRPCReturn* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>> AsyncHis_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>>(AsyncHis_WriteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>> PrepareAsyncHis_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>>(PrepareAsyncHis_WriteRaw(context, request, cq));
    }
    virtual ::grpc::Status His_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::NicSys_Hisd::psHisRPCReturn* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>> AsyncHis_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>>(AsyncHis_QueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>> PrepareAsyncHis_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>>(PrepareAsyncHis_QueryRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void His_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) = 0;
      virtual void His_Write(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) = 0;
      virtual void His_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) = 0;
      virtual void His_Query(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>* AsyncHis_WriteRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>* PrepareAsyncHis_WriteRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>* AsyncHis_QueryRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NicSys_Hisd::psHisRPCReturn>* PrepareAsyncHis_QueryRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status His_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::NicSys_Hisd::psHisRPCReturn* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>> AsyncHis_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>>(AsyncHis_WriteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>> PrepareAsyncHis_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>>(PrepareAsyncHis_WriteRaw(context, request, cq));
    }
    ::grpc::Status His_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::NicSys_Hisd::psHisRPCReturn* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>> AsyncHis_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>>(AsyncHis_QueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>> PrepareAsyncHis_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>>(PrepareAsyncHis_QueryRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void His_Write(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) override;
      void His_Write(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) override;
      void His_Query(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) override;
      void His_Query(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::NicSys_Hisd::psHisRPCReturn* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>* AsyncHis_WriteRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>* PrepareAsyncHis_WriteRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisWriteParameter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>* AsyncHis_QueryRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NicSys_Hisd::psHisRPCReturn>* PrepareAsyncHis_QueryRaw(::grpc::ClientContext* context, const ::NicSys_Hisd::psHisQueryParameter& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_His_Write_;
    const ::grpc::internal::RpcMethod rpcmethod_His_Query_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response);
    virtual ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_His_Write() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHis_Write(::grpc::ServerContext* context, ::NicSys_Hisd::psHisWriteParameter* request, ::grpc::ServerAsyncResponseWriter< ::NicSys_Hisd::psHisRPCReturn>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_His_Query() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHis_Query(::grpc::ServerContext* context, ::NicSys_Hisd::psHisQueryParameter* request, ::grpc::ServerAsyncResponseWriter< ::NicSys_Hisd::psHisRPCReturn>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_His_Write<WithAsyncMethod_His_Query<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_His_Write() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::NicSys_Hisd::psHisWriteParameter, ::NicSys_Hisd::psHisRPCReturn>(
          [this](::grpc::ServerContext* context,
                 const ::NicSys_Hisd::psHisWriteParameter* request,
                 ::NicSys_Hisd::psHisRPCReturn* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->His_Write(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_His_Query() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::NicSys_Hisd::psHisQueryParameter, ::NicSys_Hisd::psHisRPCReturn>(
          [this](::grpc::ServerContext* context,
                 const ::NicSys_Hisd::psHisQueryParameter* request,
                 ::NicSys_Hisd::psHisRPCReturn* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->His_Query(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_His_Write<ExperimentalWithCallbackMethod_His_Query<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_His_Write() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_His_Query() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_His_Write() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHis_Write(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_His_Query() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHis_Query(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_His_Write() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->His_Write(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void His_Write(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_His_Query() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->His_Query(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void His_Query(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_His_Write : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_His_Write() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::NicSys_Hisd::psHisWriteParameter, ::NicSys_Hisd::psHisRPCReturn>(std::bind(&WithStreamedUnaryMethod_His_Write<BaseClass>::StreamedHis_Write, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_His_Write() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status His_Write(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisWriteParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHis_Write(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NicSys_Hisd::psHisWriteParameter,::NicSys_Hisd::psHisRPCReturn>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_His_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_His_Query() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::NicSys_Hisd::psHisQueryParameter, ::NicSys_Hisd::psHisRPCReturn>(std::bind(&WithStreamedUnaryMethod_His_Query<BaseClass>::StreamedHis_Query, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_His_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status His_Query(::grpc::ServerContext* context, const ::NicSys_Hisd::psHisQueryParameter* request, ::NicSys_Hisd::psHisRPCReturn* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHis_Query(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NicSys_Hisd::psHisQueryParameter,::NicSys_Hisd::psHisRPCReturn>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_His_Write<WithStreamedUnaryMethod_His_Query<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_His_Write<WithStreamedUnaryMethod_His_Query<Service > > StreamedService;
};

}  // namespace NicSys_Hisd


#endif  // GRPC_NicSysHisRpc_2eproto__INCLUDED
